name: CI

on:
    pull_request:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    # scan_ruby:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v6

    #         - name: Set up Ruby
    #           uses: ruby/setup-ruby@v1
    #           with:
    #               bundler-cache: true

    #         - name: Scan for common Rails security vulnerabilities using static analysis
    #           run: bin/brakeman --no-pager

    #         - name: Scan for known security vulnerabilities in gems used
    #           run: bin/bundler-audit

    # scan_js:
    #     runs-on: ubuntu-latest

    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v6

    #         - name: Set up Ruby
    #           uses: ruby/setup-ruby@v1
    #           with:
    #               bundler-cache: true

    #         - name: Scan for security vulnerabilities in JavaScript dependencies
    #           run: bin/importmap audit

    lint:
        runs-on: ubuntu-latest
        env:
            RUBOCOP_CACHE_ROOT: tmp/rubocop
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  bundler-cache: true

            - name: Prepare RuboCop cache
              uses: actions/cache@v4
              env:
                  DEPENDENCIES_HASH: ${{ hashFiles('.ruby-version', '**/.rubocop.yml', '**/.rubocop_todo.yml', 'Gemfile.lock') }}
              with:
                  path: ${{ env.RUBOCOP_CACHE_ROOT }}
                  key: rubocop-${{ runner.os }}-${{ env.DEPENDENCIES_HASH }}-${{ github.ref_name == github.event.repository.default_branch && github.run_id || 'default' }}
                  restore-keys: |
                      rubocop-${{ runner.os }}-${{ env.DEPENDENCIES_HASH }}-

            - name: Lint code for consistent style
              run: bin/rubocop -f github

    test:
        runs-on: ubuntu-latest

        # services:
        #  redis:
        #    image: valkey/valkey:8
        #    ports:
        #      - 6379:6379
        #    options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  bundler-cache: true

            - name: Run tests
              env:
                  RAILS_ENV: test
                  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
                  SIMPLECOV_NAME: test-unit
                  # REDIS_URL: redis://localhost:6379/0
              run: bin/rails db:test:prepare test

            - name: Upload coverage
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: coverage-unit
                  path: coverage/.resultset.json
                  include-hidden-files: true

    system-test:
        runs-on: ubuntu-latest

        # services:
        #  redis:
        #    image: valkey/valkey:8
        #    ports:
        #      - 6379:6379
        #    options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  bundler-cache: true

            - name: Run System Tests
              env:
                  RAILS_ENV: test
                  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
                  SIMPLECOV_NAME: test-system
                  # REDIS_URL: redis://localhost:6379/0
              run: bin/rails db:test:prepare test:system

            - name: Upload coverage
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: coverage-system
                  path: coverage/.resultset.json
                  include-hidden-files: true

            - name: Keep screenshots from failed system tests
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: screenshots
                  path: ${{ github.workspace }}/tmp/screenshots
                  if-no-files-found: ignore

    coverage:
        runs-on: ubuntu-latest
        needs: [test, system-test]
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  bundler-cache: true

            - name: Download coverage
              uses: actions/download-artifact@v4
              with:
                  pattern: coverage-*
                  path: coverage-data

            - name: Merge and display coverage
              run: bundle exec bin/coverage_report

            - name: Upload merged coverage report
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-merged
                  path: coverage/

    deploy:
        runs-on: ubuntu-latest
        needs: [lint, test, system-test, coverage]
        if: github.ref == 'refs/heads/main'

        permissions:
            contents: read
            packages: write

        env:
            RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
            KAMAL_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
            EC2_INSTANCE_ADDRESS: ${{ secrets.EC2_INSTANCE_ADDRESS }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  bundler-cache: true

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Expose GitHub Runtime for cache
              uses: crazy-max/ghaction-github-runtime@v3

            - name: Tailscale
              uses: tailscale/github-action@v4
              with:
                  oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                  oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
                  tags: tag:ci

            - name: Deploy with Kamal
              run: bin/kamal deploy

            - name: Delete old packages
              uses: actions/delete-package-versions@v5
              with:
                  package-name: "csci3100_group_proj31"
                  package-type: "container"
                  min-versions-to-keep: 3
