require "application_system_test_case"

class DashboardTest < ApplicationSystemTestCase
  include SetupHelper

  setup do
    # Create distinct users to verify data isolation
    @seller = create_sample_user(first_name: "Seller", email_address: "seller@link.cuhk.edu.hk")
    @buyer  = create_sample_user(first_name: "Buyer",  email_address: "buyer@link.cuhk.edu.hk")
    
    # Pre-create metadata needed for items
    create_sample_communities
    create_sample_categories
    @category = Category.find_by(name: "Books")
    @community = Community.find_by(name: "Chung Chi College")
  end

  test "comprehensive dashboard flow: analytics, empty states, and offer tables" do
    # --- PHASE 1: EMPTY STATE ---
    given "a seller with no items logs in" do
      system_sign_in(@seller)
      visit dashboard_path
    end

    then_ "they see empty state illustrations and messages" do
      assert_text "Dashboard"
      assert_text "No items listed yet."
      assert_text "no pending actions"
      # Verify analytics canvas isn't rendered or is empty
      refute_selector "canvas[data-controller='item-analytics-chart']"
    end

    # --- PHASE 2: ANALYTICS TABS ---
    when_ "the seller lists items for sale" do
      @item = Item.create!(
        title: "Smart Brain Book",
        seller: @seller,
        price: 50,
        category: @category,
        community: @community,
        condition: :like_new,
        description: "Very smart."
      )
      refresh # Reload the page to see the new item
    end

    then_ "the analytics tabs appear specifically for those items" do
      within ".tabs-boxed" do
        assert_selector "input[aria-label='Smart Brain Book']"
      end
      # The chart controller should now be present
      assert_selector "canvas[data-controller='item-analytics-chart']", visible: false
    end

    # --- PHASE 3: RECEIVED OFFERS TABLE ---
    when_ "a buyer makes an offer on the seller's item" do
      @offer = Offer.create!(
        item: @item,
        buyer: @buyer,
        price_offered: 45,
        message: "I want this book!",
        status: :pending
      )
      refresh
    end

    then_ "the offer appears in the 'Received' table with correct details and actions" do
      # Use the specific row ID generated by your partial: id="received_offer_<%= offer.id %>"
      within "tr#received_offer_#{@offer.id}" do
        assert_link "Smart Brain Book", href: item_path(@item)
        assert_text "Buyer" # Checking that the buyer's name (from SetupHelper) appears
        assert_text "$45.00"
        assert_text "I want this book!"
        
        # Verify action buttons exist for the seller
        assert_button "Accept"
        assert_button "Reject"
        assert_selector "input[placeholder='Counter $']"
      end
    end

    # --- PHASE 4: DATA ISOLATION (THE 'BRAIN' CHECK) ---
    when_ "the buyer logs in to check their 'Sent' offers" do
      # Logout then login as buyer
      click_on "Log out"
      system_sign_in(@buyer)
      visit dashboard_path
    end

    then_ "they see the offer in their 'Made' table but cannot see 'Accept/Reject' buttons" do
      within "tr#sent_offer_#{@offer.id}" do
        assert_text "Smart Brain Book"
        assert_text "Seller"
        assert_text "Pending"
        
        # Security/Logic check: Buyers should NOT see Accept/Reject buttons on their own dashboard
        refute_button "Accept"
        refute_button "Reject"
        assert_button "Withdraw"
      end
    end
  end
end