require "application_system_test_case"

class RegistrationFlowTest < ApplicationSystemTestCase
  setup do
    # Clear out any emails sent before this test starts
    ActionMailer::Base.deliveries.clear
  end

  test "user registers and receives a welcome email" do
    given "a guest is on the registration page" do
      visit user_path # Adjust this path to match your routes
    end

    when_ "they fill out the registration form" do
      fill_in "First name", with: "New"
      fill_in "Last name", with: "Buyer"
      fill_in "Email", with: "new_buyer@link.cuhk.edu.hk"
      fill_in "Password", with: "password123"
      fill_in "Password confirmation", with: "password123"
      
      # We assert that clicking 'Sign up' triggers exactly 1 email
      assert_emails 1 do
        click_button "Sign up"
      end
    end

    then_ "they receive a welcome email with their name and login link" do
      mail = ActionMailer::Base.deliveries.last
      
      assert_equal ["new_buyer@link.cuhk.edu.hk"], mail.to
      assert_equal "Welcome to Group 31 platform!", mail.subject
      
      # Check the content generated by your welcome_email.html.erb
      assert_match "Welcome, New Buyer!", mail.body.encoded
      assert_match "Login to your account", mail.body.encoded
    end
  end
end